### ISSUE TITLE
どうゲームリストを作るか

### ISSUE THREAD

**Issue by NIRAer** [NIRAer/yasuiKagiya#2]
鍵屋さんについては，手動でデータベース作ればいいと思うけど
扱うゲームリストを網羅したデータベースは手動じゃ無理そう．
どっかで公開されてるか，それか売ってるか．．はたまた，自力で取得するスクリプト作るか．
いずれにせよ，どうしましょう．

**Comment by TOSUKUi** [comment]
ゴリ押しだと、片っ端から集めて、クラスタリングしていくとかですね。
steamのゲームに絞ったりするなら、steamのゲームリストを取得する方法を考えるといい気がする。

**Comment by TOSUKUi** [comment]
Steam apiを叩いてみるか。あったら

**Comment by NIRAer** [comment]
プラットフォーム毎(Steam, Origin, Uplayなど)にリストの取得方法は確立していく必要ありそうだね．
steam apiちょい見た感じ，app_idからゲームの情報取るのは簡単にできそうだけど，肝心のapp_idリストの取り方が見つからなかった．．

steam api調べたついでに余談
[SteamDB](https://steamdb.info/)ってサイト運営してるとこのgitリポジトリに公開されてるプロジェクト複数あるし色々参考にできそう．
[https://github.com/SteamDatabase](https://github.com/SteamDatabase)

**Comment by NIRAer** [comment]
#9 に引き継ぎ
