### ISSUE TITLE
DB接続の実装に関して

### ISSUE THREAD

**Issue by NIRAer** [NIRAer/yasuiKagiya#4]
ServletからのDB接続は**DAOパターン**で実装する．
- DAOパターンとは？  
DAO(Data Access Object)の名のとおり，DAOオブジェクトがインタフェースになる．DBから情報が欲しい時は，daoオブジェクトから情報をとってくる感じ．（一々dbを意識する必要がなくなる）  
- DAOの実装方法  
DaoクラスとDBから取得した情報を入れとくオブジェクトクラスの実装が必要．DaoクラスにはfindAllとか必要なメソッドを適宜実装．オブジェクトクラスにはセッターゲッターを実装する．詳細な実装は，コードを参考に

**Comment by TOSUKUi** [comment]
意味はわかった
