### ISSUE TITLE
全体の設計を先に提示するか一緒に考えたい

### ISSUE THREAD

**Issue by TOSUKUi** [NIRAer/yasuiKagiya#5]
全体の設計を先に共有しておけば、どこを誰がやるかを考えやすいと思われる。
実装方法がそもそもわかっていない分野を含んでいるので、そこに関してはそもそも解決策が考えつかないのだ。

**Comment by NIRAer** [comment]
実装面での設計やDB設計などやること色々共有したいね．
特に図表などでまとめて共有したいとこ．．(開発者増えたり，後で見直す用)
現時点でザックりと必要な成果物を書くと，  
**webクローラー（実装は何でもいい） + webサーバ(サーブレット+JSP) + DBサーバ（MySQL)**  
クローリングに関して，TOSUさん詳しそうなんで，色々参考にしたいな．  
前紹介したJauntは毎月ラインセンス更新するのがチョイ面倒かも．  
後，今目付けてるのが，Node.js．実装楽(http://www.amazon.co.jp/dp/4883379930)  
他に色々候補挙げてもらって，良さそうなのを採用しましょう

**Comment by NIRAer** [comment]
やっていくことを列挙して，それぞれ取り掛かれるようにしたいので，
必要なタスクの洗い出しをやりたいです．
空いてる時間にTSにて，話し合いましょう

**Comment by NIRAer** [comment]
クローラ設計で参考になりそうな記事を発見
[http://qiita.com/emuq/items/7e114608369944ebc289](http://qiita.com/emuq/items/7e114608369944ebc289)

**Comment by NIRAer** [comment]
#7 こちらへ
