### ISSUE TITLE
webページ設計

### ISSUE THREAD

**Issue by NIRAer** [NIRAer/yasuiKagiya#6]
トップページの構成とページの遷移図
![homepage](https://cloud.githubusercontent.com/assets/7260243/13062484/63dd2218-d482-11e5-8635-82105fe341db.png)
![overall view](https://cloud.githubusercontent.com/assets/7260243/13062485/65141f60-d482-11e5-89dc-ab499904bf0e.png)

**Comment by NIRAer** [comment]
いまやってる

**Comment by TOSUKUi** [comment]
承知

**Comment by NIRAer** [comment]
引き継ぎ
https://github.com/Yasukagi/yasuiKagiya/issues/3
